# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(a6935d04-799b-4c3f-8d6d-bbab410e1917)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name $resourceGroupName  --location $location
      az deployment group create --resource-group $resourceGroupName --template-file main.bicep

